var data = {
    categories: ['Action', 'Animation', 'Comedy', 'Horror'],
    max_rating: 5,
    films: [
    //   {
    //     src: 'TIE+Fighter+-+short+film(720p).mp4',
    //     img_url: './img/tiefighter.png',
    //     title: 'TIE Fighter',
    //     duration: '7:27',
    //     author: 'OtaKing77077',
    //     author_url: 'https://www.youtube.com/channel/UCRBNWKYrybXl2Un6-ejwx8g',
    //     description: 'hat if there was an Empire-focussed short Star Wars animation, drawn with the crazy detail and shading of classic 80s anime that\'s all but vanished from Japan nowadays? Well, I tried my best. Apologies in advance for not living up to Venus Wars standards. Drawn and animated by yours truly over 4 years\' worth of weekends, with music by the living guitar solo Zak Rahman and sound design by up and coming audio technician Joseph Leyva. Fans of Lucasarts\' seminal 1994 TIE Fighter game may notice a few familiar sights and sounds. That “incoming missile” noise gives me horrible flashbacks to this day...',
    //     year: 2015,
    //     audio_language: 'N/A',
    //     sub_language: 'N/A',
    //     rating: 4,
    //     category: 'Animation'
    // },
        {
        src: 'Naruto+Live+Action+(avec+Florian+Nguyen+et+Aziatomik)(720p).mp4',
        img_url: './img/narutoaction.png',
        title: 'Naruto Live Action',
        duration: '1:47',
        author: 'Brice Duan',
        author_url: 'https://www.youtube.com/channel/UCYF-3u_Jh5lWzPG2gRDD3-Q',
        description: 'Naruto Live Action - "L\'Héritage". Un membre de l\'Akatsuki est venu défier les héritiers de Naruto ! Il s\'agit d\'un fan film rendant hommage à l\'oeuvre de Masashi Kishimito. Merci à Rivenx3i pour m\'avoir inspiré avec sa vidéo Naruto Shippuden Dreamers Fight, le meilleur fan film sur Naruto à ce jour',
        year: 2013,
        audio_language: 'Français',
        sub_language: 'N/A',
        rating: 3,
        category: 'Action'
    }, {
        src: 'Dragon+Ball+vs+Naruto.+Anime+fight.(720p).mp4',
        img_url: './img/narutovsgoku.png',
        title: 'Dragon Ball vs Naruto',
        duration: '8:39',
        author: 'Alberto Barberá',
        author_url: 'https://www.youtube.com/channel/UCaH3HAq1O9rJvTUn0mlVVkw',
        description: 'Pelea brutal con un toque de humor y comedia. La idea surgió jugando al Dragon Ball Xenoverse después de leer el manga de Naruto Shippuden mientras me convertía en Super Saiyan y escuchaba el rap de Naruto y Sasuke. Love Dragon Ball games. Waiting for Naruto Gaiden to come soon... Mientras disfrutemos de DB Super.',
        year: 2015,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 5,
        category: 'Action'
    }, {
        src: 'Naruto+Shippuden_+Dance+of+War+-+Short+Film+(Turn+On+Subtitles)(1080p).mp4',
        img_url: './img/danceofwar.png',
        title: 'Naruto Shippuden : Dance of War',
        duration: '7:48',
        author: 'RivenX3i',
        author_url: 'https://www.youtube.com/channel/UC-Op8pOVwbeqp6lyL2xJvqQ',
        description: 'The 4th Great Ninja War is near. Two Hidden Leaf ninja say goodbye to where they grew into ninja, by holding a ceremony to test their own resolve.',
        year: 2015,
        audio_language: 'Japonais',
        sub_language: 'N/A',
        rating: 4,
        category: 'Action'
    }, {
        src: 'NARUTO+-+New+Movie+2018+-+Full+Trailer+AMAZING!!(720p).mp4',
        img_url: './img/newnaruto.png',
        title: 'New Naruto',
        duration: '12:50',
        author: 'RivenX3i',
        author_url: 'https://www.youtube.com/channel/UC-Op8pOVwbeqp6lyL2xJvqQ',
        description: 'The 4th Great Ninja War is near. Two Hidden Leaf ninja say goodbye to where they grew into ninja, by holding a ceremony to test their own resolve.',
        year: 2016,
        audio_language: 'Japonais',
        sub_language: 'N/A',
        rating: 3,
        category: 'Action'
    }, {
        src: 'Naruto+The+Movie!+(Official+Fake+Trailer)(720p).mp4',
        img_url: './img/ryansiewnaruto.png',
        title: 'Naruto, The Movie',
        duration: '3:15',
        author: 'nigahiga',
        author_url: 'https://www.youtube.com/channel/UCSAUGyc_xA8uYzaIVG6MESQ',
        description: 'Huge THANK YOU to Portal A, Gritty Reboots and everyone on the Japan team for helping out with this! #grubblife',
        year: 2013,
        audio_language: 'Anglais',
        sub_language: 'N/A',
        rating: 3,
        category: 'Comedy'
    }, {
        src: 'Red+Hood_+The+Fallen+-+DC+Comic+Batman+Fan+Film(720p).mp4',
        img_url: './img/redhood.png',
        title: 'Red Hood : The Fallen',
        duration: '23:16',
        author: 'Toby Bajrovic',
        author_url: 'https://www.youtube.com/channel/UCjGUxyIEtqh_CyWBIVIhzng',
        description: 'Red Hood: The Fallen is a fan made DC Comic film produced in Perth, Western Australia.',
        year: 2015,
        audio_language: 'Anglais',
        sub_language: 'N/A',
        rating: 5,
        category: 'Action'
    }, {
        src: 'JUSTICE+LEAGUE_+Trinity+Force+_+DC+FAN+FILM+_(720p).mp4',
        img_url: './img/justiceleague.png',
        title: 'Justice League : Trinity Force',
        duration: '16:29',
        author: 'SHIELDS Productions',
        author_url: 'https://www.youtube.com/channel/UCaz9yZYvDvbG_mgPhcCn4pw',
        description: 'Four months after an earth shattering event, Broken, The Justice League must put their differences aside to stop The Joker!',
        year: 2015,
        audio_language: 'Anglais',
        sub_language: 'N/A',
        rating: 2.5,
        category: 'Action'
    }, {
        src: 'The+Mad+Hatter+-+Fan+Film(720p).mp4',
        img_url: './img/madhatter.png',
        title: 'The Mad Hatter',
        duration: '6:16',
        author: 'Wolfspider Productions',
        author_url: 'https://www.youtube.com/channel/UC_BAlJSUbpqzSjNX8on3Rgw',
        description: 'A dark modern interpretation on the DC comic villain, Jervis Tetch aka The Mad Hatter. Set in the time of the modern interpretations on Alice in Wonderland.',
        year: 2016,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 2,
        category: 'Horror'
    }, {
        src: 'The+Flash+Lite+(comedy+fan+film)(720p).mp4',
        img_url: './img/flashlite.png',
        title: 'The Flash Lite',
        duration: '10:14',
        author: 'The Chublin Brothers',
        author_url: 'https://www.youtube.com/channel/UCPFmTZlrfUkRCjGgSLtqx1g',
        description: 'A world-class athlete, but otherwise ordinary guy, assumes the identity of The Flash after being named the "Fastest Man Alive."  But will being slightly faster than everyone else, with exactly zero superpowers, give him the crime-fighting edge he needs?',
        year: 2013,
        audio_language: 'Anglais',
        sub_language: 'N/A',
        rating: 4,
        category: 'Comedy'
    }, {
        src: 'Clash+at+the+Cantina+(2014)+-+Star+Wars+Fan+Film(720p).mp4',
        img_url: './img/cantinaclash.png',
        title: 'Clash at the Cantina',
        duration: '4:45',
        author: 'Corey Vidal',
        author_url: 'https://www.youtube.com/channel/UCRBNWKYrybXl2Un6-ejwx8g',
        description: 'As part of the on-going Star Wars-inspired action comedy video series between YouTubers Corey Vidal (ApprenticeA) and Craig Benzine (Wheezy Waiter), the guys take the battle to the Cantina with a new lightsaber fight.',
        year: 2014,
        audio_language: 'Anglais',
        sub_language: 'N/A',
        rating: 4,
        category: 'Comedy'
    }, {
        src: 'THE+74th+HUNGER+GAMES+(SHORT+COMEDY+FAN+FILM)(720p).mp4',
        img_url: './img/hungergames.png',
        title: 'The 74th Hunger Games',
        duration: '4:24',
        author: 'ChickenFeetFilms',
        author_url: 'https://www.youtube.com/channel/UC9nzWgRq-cQcakkzZq1XZvg',
        description: 'A short "HUNGER GAMES" fan film, made by ChickenFeetFilms. Music provided by boyinaband.com http://bit.ly/PLrd1Y',
        year: 2012,
        audio_language: 'Anglais',
        sub_language: 'N/A',
        rating: 2,
        category: 'Comedy'
    }, {
        src: 'VICTIM+-+A+Short+Slender+Man+Horror+Film(720p).mp4',
        img_url: './img/slenderman.png',
        title: 'Victime',
        duration: '14:30',
        author: 'Eddie Adamson',
        author_url: 'https://www.youtube.com/channel/UCpWweEWZIfalXgKS1xO2RDw',
        description: 'This is a Short Horror film I made for my last college project in Creative Media Production, before I went off to University. We were given the chance to individually make a film of our own choice, of varied length and subject matter.',
        year: 2013,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 4,
        category: 'Horror'
    }, {
        src: 'DON&#039;T+MOVE+-+A+Short+Horror+Film+(2017)(720p).mp4',
        img_url: './img/dontmove.png',
        title: 'Fallout',
        duration: '7:27',
        author: 'AndrewProductionsTV',
        author_url: 'https://www.youtube.com/channel/UCOAHgaVjyUjFtxhgCAQ_vAg',
        description: '►FALLOUT -  Apocalyptic Thriller Short Film Aaron, a young researcher seeks to discover the deadly disease that plagues Earth. This project is meant to convey the philosophical message that Humans are the deadliest beings to ever walk the Earth through Industrialism, Animal Cruelty/Exploitation, and War. ',
        year: 2015,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 3,
        category: 'Horror'
    }, {
        src: 'Dragon+Ball+Z_+Light+of+Hope+-+Pilot(720p).mp4',
        img_url: './img/lightofhope.png',
        title: 'Dragon Ball Z : Light of Hope',
        duration: '13:14',
        author: 'RobotUnderdog2',
        author_url: 'https://www.youtube.com/channel/UCkeLPTcjQm3zlPuDdvS4gvg',
        description: 'This series is an adaptation of “The History of Trunks” TV Special. In this timeline, Goku & the other Z Warriors are dead. This is the story of Gohan & Trunks in their battle to survive against the Androids.',
        year: 2015,
        audio_language: 'Anglais',
        sub_language: 'N/A',
        rating: 4,
        category: 'Action'
    }, {
        src: 'Attack+on+Titan+-+LEVI+vs+BEAST+TITAN+-+Fan+made+animation+-+Shingeki+no+kyojin+manga+chapter+81(480p).mp4',
        img_url: './img/attackontitan.png',
        title: 'Attack on Titan',
        duration: '1:14',
        author: 'S.L.H Animation',
        author_url: 'https://www.youtube.com/channel/UCE6CEl3ZoiDLUhawFG5xn1g',
        description: 'It is a fan made animation of Attack on Titan. It was for fun and I do not own right to Attack in Titan. All credit go to WIT studio, Production I.G, and Hajime Isayama for such amazing series.',
        year: 2017,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 4,
        category: 'Animation'
    }, {
        src: 'Chinese+teenager+created+awesome+fight+scene+animation(536p).mp4',
        img_url: './img/fightanimation.png',
        title: 'Heat vs Repulsion',
        duration: '3:50',
        author: 'magnil',
        author_url: 'https://www.youtube.com/channel/UCRBNWKYrybXl2Un6-ejwx8g',
        description: '中国19岁学生制作的个人动画短片《高温vs排斥》，作者：光学核心(Optical-Core)。概念、动画、背景、合成均由作者个人完成。',
        year: 2015,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 5,
        category: 'Animation'
    }, {
        src: 'SPAWN_+THE+RECALL+-+FAN+FILM(720p).mp4',
        img_url: './img/spawn.png',
        title: 'Spawn : The Recall',
        duration: '7:56',
        author: 'Irissee',
        author_url: 'https://www.youtube.com/channel/UCefxt5RuoiBlanGXmh4vg_A',
        description: 'SPAWN : THE RECALL is the story of a former witch and her son, who try to live a normal life away from the darkness.',
        year: 2014,
        audio_language: 'Anglais',
        sub_language: 'N/A',
        rating: 4,
        category: 'Horror'
    }, {
        src: '[Rebeler]+Madara+VS+Hashirama+-+Cosplay+Movie(720p).mp4',
        img_url: './img/cosplayfight.png',
        title: 'Madara VS Hashirama',
        duration: '8:06',
        author: 'Rebeler Team',
        author_url: 'https://www.youtube.com/channel/UCSDJAB-afLRrbytxQuq-lAg',
        description: 'REBELER adalah Organisasi Cosplay yang Independent berbentuk Team di daerah Bojonegoro - Jawa Timur, yang mempunyai tujuan untuk mengembangkan kreativitas para membernya dalam dunia percosplayan',
        year: 2016,
        audio_language: 'N/A',
        sub_language: 'N/A',
        rating: 4,
        category: 'Action'
    }, ]
};
